services:
  postgresql18:
    image: postgres:18
    container_name: postgresql18-simple
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgresql18-simple-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  sysbench-proxysql:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: sysbench-proxysql
    depends_on:
      postgresql18:
        condition: service_healthy
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWD}
      DB_NAME: ${DB_NAME}
      DB_HOST: localhost
      DB_PORT: ${PROXY_DB_PORT:-6132}
      PROXY_ADMIN_USER: admin
      PROXY_ADMIN_PASSWD: admin
    ports:
      - "${PROXY_DB_PORT}:6133"
      - "${PROXY_ADMIN_PORT}:6132"
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
      - sysbench-proxysql-data:/var/lib/proxysql

volumes:
  postgresql18-simple-data:
  sysbench-proxysql-data:
